sensors:
  right_bins_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  kts1_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]

  conveyor_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-0.65, 3.7, 1.2]
      rpy: [pi, pi/2, 0]

  breakbeam_0:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.403512, 3.871046, 0.880000]
      rpy: [0, 0, pi]

  breakbeam_1:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.409806, -4.152406, 0.88]
      rpy: [0, 0, pi]
  